export const Router = {
  // App URL
  appUrlBase: process.env.REACT_APP_URL,
  appHome: '/',
  appLogin: '/login',
  appSignUp: '/signup',
  appLogout: '/logout',
  appResetPassword: '/reset-password',
  appResetPasswordConfirm: '/reset-password-confirm/:token',
  appIndexCardHolder: '/dashboard/index-card-holder',
  appMedicalHistoriesConfig: '/dashboard/medical-histories-config',
  appSearchMedicalHistoriesConfig: '/dashboard/search-medical-histories-config',
  appSchedule: '/dashboard/schedule',
  appClinicalHistories: '/dashboard/clinical-histories',
  appAssignAppointment: '/dashboard/assign-appointment',

  // API URI
  apiUrlBase: process.env.REACT_APP_API_URL,
  apiLogin: '/api/login/',
  apiResetPassword: '/api/reset-password/',
  apiResetPasswordConfirm: '/api/reset-password/confirm/',
  apiIndexCardHolder: '/api/index-card-holder/',
  apiNacionalities: '/api/nacionalities/',
  apiCountries: '/api/countries/',
  apiDiagnoses: '/api/diagnoses/',
  apiCategories: '/api/categories/',
  apiDeparments: '/api/deparments/:countryId',
  apiCities: '/api/cities/:deparmentId',
  apiUsualOccupations: '/api/usual-occupation/',
  apiSpecialPopulations: '/api/special-population/',
  apiSexualOrientations: '/api/sexual-orientation/',
  apiSocialSecuritySchemes: '/api/social-security-scheme/',
  apiEps: '/api/eps/',
  apiCivilStatus: '/api/civil-status/',
  apiScholarship: '/api/scholarship/',
  apiEthnicGroup: '/api/ethnic-group/',
  apiTypeDegreeDisability: '/api/type-degree-disability/',
  apiTypeRequest: '/api/type-request/',
  apiState: '/api/state/',
  apiProgram: '/api/program/',
  apiProductionCenter: '/api/production-center/',
  apiIps: '/api/ips/',
  apiRelationshipPersonInCharge: '/api/relationship-person-in-charge/',
  apiHcOpenPlace: '/api/hc-open-place/',
  apiHcTransferTo: '/api/hc-transfer-to/',
  apiHcConfig: '/api/medical-history-config/',
  apiUserHc: '/api/user-medical-history/',
  apiUser: '/api/user/',
  apiUserHcDetail: '/api/user-medical-history-detail/:umh_id',
  apiHcConfigDetail: '/api/medical-history-config-detail/:hc_id',
  apiAvailabilities: '/api/availabilities/',
  apiUserAvailabilities: '/api/user-availabilities/',
  apiAppointments: '/api/schedules/',
  apiReschedule: '/api/reschedule/',
}
